{"user":"x_finder3","timestamp":"2024-09-03T09:45:28.583198","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:45:28.584208","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:45:28.584322","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:45:28.584415","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:45:28.682456","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:45:33.582632","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:45:33.583091","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:46:28.735890","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:46:28.741968","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:46:28.742369","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:46:28.743262","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:46:28.743443","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:46:28.744303","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:46:28.745270","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:46:28.745408","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:46:28.745511","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:46:28.843145","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:46:33.743364","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:46:33.743983","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.325474","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.330318","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.330683","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.331188","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.331325","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.331906","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.332589","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.332706","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.332801","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:29.431177","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:34.331318","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:47:34.331853","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.480848","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.485955","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.486318","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.486819","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.486957","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.487549","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.488309","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.488425","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.488520","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:29.586845","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:34.486941","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:48:34.487392","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.108968","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.124803","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.125187","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.125953","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.126135","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.126908","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.127947","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.128091","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.128198","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:30.225941","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:35.126080","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:49:35.126620","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.331304","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.336532","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.336893","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.337474","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.337677","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.338298","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.339041","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.339174","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.339277","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:30.437446","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:35.337589","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:50:35.338165","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.180417","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.186910","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.187306","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.188213","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.188406","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.189271","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.190327","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.190461","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.190566","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:30.288176","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:35.188353","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:51:35.189006","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.775874","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.781902","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.782254","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.783051","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.783231","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.784024","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.784982","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.785105","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.785202","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:30.883046","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:35.783174","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:52:35.783683","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.846410","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.851399","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.851766","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.852262","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.852395","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.852948","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.853643","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.853757","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.853852","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:30.952258","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:35.852384","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:53:35.852893","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:30.850318","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:30.855545","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:30.855913","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:30.856437","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:30.856587","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:30.857169","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:30.857914","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:30.858043","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:30.858143","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:30.956430","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:35.856559","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:54:35.857096","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.264187","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.269689","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.270050","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.270619","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.270765","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.271319","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.272019","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.272138","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.272235","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:31.370592","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:36.270722","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:55:36.271170","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:32.002892","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:32.007663","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:32.008017","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:32.008500","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:32.008635","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:32.009190","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:32.009874","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:32.009991","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:32.010088","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:32.108486","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:37.008627","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:56:37.009117","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.074059","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.079612","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.080005","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.080598","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.080750","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.081351","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.082091","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.082214","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.082314","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:32.180602","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:37.080710","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:57:37.081214","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.358816","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.364110","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.364476","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.364988","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.365125","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.365695","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.366387","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.366498","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.366599","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:32.464986","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:37.365106","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:58:37.365607","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.661253","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.666209","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.666565","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.667120","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.667268","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.667848","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.668549","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.668665","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.668760","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:32.767051","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:37.667221","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T09:59:37.667775","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.566613","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.572599","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.573027","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.573592","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.573746","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.574387","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.575190","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.575321","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.575424","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:32.673585","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:37.573708","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:00:37.574336","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.950467","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.956542","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.956947","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.957727","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.957906","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.958700","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.959626","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.959759","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:32.959863","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:33.057727","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:37.957829","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:01:37.958419","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.129895","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.135663","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.136009","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.136704","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.136866","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.137585","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.138509","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.138627","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.138731","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:33.236697","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:38.136825","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:02:38.137337","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:33.195755","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:33.201891","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:33.202260","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:33.203054","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:33.203243","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:33.204106","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:33.205090","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:33.205215","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:33.205320","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:33.303037","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:38.203186","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:03:38.203767","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.489137","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.494312","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.494688","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.495173","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.495311","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.495849","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.496536","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.496649","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.496744","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:33.595180","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:38.495294","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:04:38.495805","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.770510","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.776203","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.776551","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.777256","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.777432","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.778258","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.779168","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.779293","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.779389","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:33.877273","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:38.777365","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:05:38.777956","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.475179","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.481198","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.481579","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.482400","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.482586","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.483427","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.484478","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.484608","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.484723","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:33.582419","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:38.482519","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:06:38.482975","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.822592","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.828128","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.828531","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.829154","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.829309","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.829923","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.830658","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.830783","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.830885","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:33.929110","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:38.829250","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:07:38.829803","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.209922","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.216515","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.216918","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.217750","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.217942","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.218739","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.219682","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.219815","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.219920","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:34.317665","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:39.217845","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:08:39.218536","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.134306","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.139351","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.139702","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.140275","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.140413","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.140952","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.141655","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.141773","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.141867","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:34.240275","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:39.140397","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:09:39.140854","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.530864","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.537026","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.537422","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.538004","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.538163","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.538796","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.539589","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.539717","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.539819","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:34.637994","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:39.538124","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:10:39.538687","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.361811","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.366956","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.367351","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.367908","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.368046","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.368649","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.369354","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.369465","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.369559","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:34.467938","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:39.368028","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:11:39.368525","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.036346","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.041537","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.041899","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.042457","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.042596","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.043156","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.043883","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.043995","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.044091","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:35.142463","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:40.042580","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:12:40.043027","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.215292","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.221156","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.221519","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.222220","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.222394","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.223163","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.224054","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.224175","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.224272","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:35.322210","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:40.222342","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:13:40.222904","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.189022","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.194370","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.194731","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.195255","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.195394","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.195989","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.196728","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.196846","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.196942","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:35.295249","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:40.195387","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:14:40.195871","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.334732","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.340132","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.340592","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.341155","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.341307","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.341926","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.342681","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.342808","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.342917","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:35.441158","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:40.341273","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:15:40.341850","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.329284","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.335752","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.336150","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.337073","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.337262","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.338096","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.339505","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.339683","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.339789","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:35.437025","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:40.337178","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:16:40.337831","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.740366","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.745549","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.745900","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.746578","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.746731","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.747505","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.748405","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.748538","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.748640","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:35.846558","nav_name":"api_owasp4","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:40.746692","nav_name":"api_owasp4","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:17:40.747304","nav_name":"api_owasp4","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:18:35.748789","nav_name":"api_owasp4","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:18:35.754678","nav_name":"api_owasp4","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:18:35.755026","nav_name":"api_owasp4","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:18:35.755751","nav_name":"api_owasp4","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:18:35.755925","nav_name":"api_owasp4","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:18:35.756793","nav_name":"api_owasp4","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:18:35.757765","nav_name":"api_owasp4","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:18:35.757888","nav_name":"api_owasp4","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:18:35.757984","nav_name":"api_owasp4","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
