{"user":"x_finder3","timestamp":"2024-09-03T10:32:39.149837","nav_name":"api_owasp_2_3","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:39.150290","nav_name":"api_owasp_2_3","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:39.150406","nav_name":"api_owasp_2_3","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:39.247815","nav_name":"api_owasp_2_3","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:44.148002","nav_name":"api_owasp_2_3","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:44.148527","nav_name":"api_owasp_2_3","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:39.432070","nav_name":"api_owasp_2_3","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:39.437887","nav_name":"api_owasp_2_3","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:39.438248","nav_name":"api_owasp_2_3","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:39.439368","nav_name":"api_owasp_2_3","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:39.439541","nav_name":"api_owasp_2_3","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:39.440222","nav_name":"api_owasp_2_3","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:39.441040","nav_name":"api_owasp_2_3","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:39.441160","nav_name":"api_owasp_2_3","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:39.441270","nav_name":"api_owasp_2_3","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:39.539326","nav_name":"api_owasp_2_3","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:44.439489","nav_name":"api_owasp_2_3","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:44.439982","nav_name":"api_owasp_2_3","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:39.799302","nav_name":"api_owasp_2_3","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:39.804952","nav_name":"api_owasp_2_3","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:39.805352","nav_name":"api_owasp_2_3","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:39.806117","nav_name":"api_owasp_2_3","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:39.806256","nav_name":"api_owasp_2_3","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:39.806849","nav_name":"api_owasp_2_3","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:39.807674","nav_name":"api_owasp_2_3","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:39.807795","nav_name":"api_owasp_2_3","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:39.807897","nav_name":"api_owasp_2_3","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:39.906143","nav_name":"api_owasp_2_3","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:44.806214","nav_name":"api_owasp_2_3","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:44.806705","nav_name":"api_owasp_2_3","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:40.088062","nav_name":"api_owasp_2_3","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:40.093726","nav_name":"api_owasp_2_3","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:40.094086","nav_name":"api_owasp_2_3","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:40.094968","nav_name":"api_owasp_2_3","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:40.095111","nav_name":"api_owasp_2_3","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:40.095686","nav_name":"api_owasp_2_3","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:40.096396","nav_name":"api_owasp_2_3","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:40.096515","nav_name":"api_owasp_2_3","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:40.096621","nav_name":"api_owasp_2_3","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:40.194980","nav_name":"api_owasp_2_3","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:45.095090","nav_name":"api_owasp_2_3","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:45.095568","nav_name":"api_owasp_2_3","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:40.004443","nav_name":"api_owasp_2_3","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:40.009299","nav_name":"api_owasp_2_3","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:40.009688","nav_name":"api_owasp_2_3","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:40.010520","nav_name":"api_owasp_2_3","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:40.010668","nav_name":"api_owasp_2_3","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:40.011250","nav_name":"api_owasp_2_3","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:40.011962","nav_name":"api_owasp_2_3","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:40.012073","nav_name":"api_owasp_2_3","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:40.012175","nav_name":"api_owasp_2_3","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:40.110523","nav_name":"api_owasp_2_3","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:45.010610","nav_name":"api_owasp_2_3","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:45.011045","nav_name":"api_owasp_2_3","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:40.467898","nav_name":"api_owasp_2_3","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:40.473408","nav_name":"api_owasp_2_3","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:40.473812","nav_name":"api_owasp_2_3","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:40.474583","nav_name":"api_owasp_2_3","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:40.474727","nav_name":"api_owasp_2_3","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:40.475347","nav_name":"api_owasp_2_3","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:40.476070","nav_name":"api_owasp_2_3","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:40.476192","nav_name":"api_owasp_2_3","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:40.476296","nav_name":"api_owasp_2_3","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:40.574573","nav_name":"api_owasp_2_3","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:45.474711","nav_name":"api_owasp_2_3","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:45.475244","nav_name":"api_owasp_2_3","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:40.825305","nav_name":"api_owasp_2_3","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:40.831715","nav_name":"api_owasp_2_3","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:40.832106","nav_name":"api_owasp_2_3","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:40.833405","nav_name":"api_owasp_2_3","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:40.833596","nav_name":"api_owasp_2_3","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:40.834380","nav_name":"api_owasp_2_3","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:40.835443","nav_name":"api_owasp_2_3","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:40.835573","nav_name":"api_owasp_2_3","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:40.835682","nav_name":"api_owasp_2_3","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:40.933368","nav_name":"api_owasp_2_3","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:45.833534","nav_name":"api_owasp_2_3","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:45.834113","nav_name":"api_owasp_2_3","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:40.912255","nav_name":"api_owasp_2_3","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:40.917220","nav_name":"api_owasp_2_3","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:40.917574","nav_name":"api_owasp_2_3","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:40.918353","nav_name":"api_owasp_2_3","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:40.918494","nav_name":"api_owasp_2_3","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:40.919063","nav_name":"api_owasp_2_3","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:40.919789","nav_name":"api_owasp_2_3","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:40.919900","nav_name":"api_owasp_2_3","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:40.920002","nav_name":"api_owasp_2_3","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:41.018348","nav_name":"api_owasp_2_3","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:45.918483","nav_name":"api_owasp_2_3","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:45.918939","nav_name":"api_owasp_2_3","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:41.212997","nav_name":"api_owasp_2_3","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:41.218047","nav_name":"api_owasp_2_3","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:41.218427","nav_name":"api_owasp_2_3","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:41.219185","nav_name":"api_owasp_2_3","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:41.219337","nav_name":"api_owasp_2_3","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:41.219936","nav_name":"api_owasp_2_3","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:41.220645","nav_name":"api_owasp_2_3","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:41.220767","nav_name":"api_owasp_2_3","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:41.220873","nav_name":"api_owasp_2_3","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:41.319176","nav_name":"api_owasp_2_3","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:46.219301","nav_name":"api_owasp_2_3","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:46.219877","nav_name":"api_owasp_2_3","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:41.397901","nav_name":"api_owasp_2_3","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:41.402863","nav_name":"api_owasp_2_3","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:41.403217","nav_name":"api_owasp_2_3","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:41.403923","nav_name":"api_owasp_2_3","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:41.404058","nav_name":"api_owasp_2_3","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:41.404612","nav_name":"api_owasp_2_3","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:41.405294","nav_name":"api_owasp_2_3","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:41.405410","nav_name":"api_owasp_2_3","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:41.405510","nav_name":"api_owasp_2_3","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:41.503926","nav_name":"api_owasp_2_3","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:46.404045","nav_name":"api_owasp_2_3","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:46.404508","nav_name":"api_owasp_2_3","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:41.344322","nav_name":"api_owasp_2_3","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:41.349456","nav_name":"api_owasp_2_3","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:41.349838","nav_name":"api_owasp_2_3","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:41.350618","nav_name":"api_owasp_2_3","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:41.350763","nav_name":"api_owasp_2_3","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:41.351336","nav_name":"api_owasp_2_3","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:41.352015","nav_name":"api_owasp_2_3","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:41.352126","nav_name":"api_owasp_2_3","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:41.352226","nav_name":"api_owasp_2_3","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:41.450627","nav_name":"api_owasp_2_3","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:46.350741","nav_name":"api_owasp_2_3","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:46.351202","nav_name":"api_owasp_2_3","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:41.633615","nav_name":"api_owasp_2_3","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:41.639328","nav_name":"api_owasp_2_3","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:41.639763","nav_name":"api_owasp_2_3","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:41.640596","nav_name":"api_owasp_2_3","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:41.640743","nav_name":"api_owasp_2_3","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:41.641340","nav_name":"api_owasp_2_3","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:41.642060","nav_name":"api_owasp_2_3","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:41.642183","nav_name":"api_owasp_2_3","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:41.642294","nav_name":"api_owasp_2_3","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:41.740630","nav_name":"api_owasp_2_3","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:46.640714","nav_name":"api_owasp_2_3","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:46.641151","nav_name":"api_owasp_2_3","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:41.679003","nav_name":"api_owasp_2_3","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:41.684065","nav_name":"api_owasp_2_3","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:41.684460","nav_name":"api_owasp_2_3","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:41.685205","nav_name":"api_owasp_2_3","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:41.685342","nav_name":"api_owasp_2_3","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:41.685936","nav_name":"api_owasp_2_3","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:41.686631","nav_name":"api_owasp_2_3","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:41.686742","nav_name":"api_owasp_2_3","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:41.686840","nav_name":"api_owasp_2_3","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:41.785228","nav_name":"api_owasp_2_3","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:46.685335","nav_name":"api_owasp_2_3","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:46.685795","nav_name":"api_owasp_2_3","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:42.203812","nav_name":"api_owasp_2_3","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:42.208985","nav_name":"api_owasp_2_3","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:42.209350","nav_name":"api_owasp_2_3","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:42.210064","nav_name":"api_owasp_2_3","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:42.210202","nav_name":"api_owasp_2_3","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:42.210749","nav_name":"api_owasp_2_3","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:42.211427","nav_name":"api_owasp_2_3","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:42.211546","nav_name":"api_owasp_2_3","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:42.211648","nav_name":"api_owasp_2_3","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:42.310090","nav_name":"api_owasp_2_3","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:47.210195","nav_name":"api_owasp_2_3","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:47.210667","nav_name":"api_owasp_2_3","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:42.289878","nav_name":"api_owasp_2_3","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:42.295856","nav_name":"api_owasp_2_3","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:42.296251","nav_name":"api_owasp_2_3","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:42.297489","nav_name":"api_owasp_2_3","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:42.297687","nav_name":"api_owasp_2_3","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:42.298458","nav_name":"api_owasp_2_3","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:42.299281","nav_name":"api_owasp_2_3","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:42.299396","nav_name":"api_owasp_2_3","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:42.299496","nav_name":"api_owasp_2_3","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:42.397452","nav_name":"api_owasp_2_3","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:47.297610","nav_name":"api_owasp_2_3","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:47.298136","nav_name":"api_owasp_2_3","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:42.652548","nav_name":"api_owasp_2_3","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:42.658187","nav_name":"api_owasp_2_3","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:42.658601","nav_name":"api_owasp_2_3","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:42.659388","nav_name":"api_owasp_2_3","action":"组件启动","params":"数据窗口函数-1, 定时任务函数--1","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:42.659548","nav_name":"api_owasp_2_3","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:42.660195","nav_name":"api_owasp_2_3","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:42.660937","nav_name":"api_owasp_2_3","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:42.661056","nav_name":"api_owasp_2_3","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:42.661161","nav_name":"api_owasp_2_3","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:42.759372","nav_name":"api_owasp_2_3","action":"停止","params":"数据窗口任务停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:47.659513","nav_name":"api_owasp_2_3","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:47.660064","nav_name":"api_owasp_2_3","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
