{"user":"x_finder3","timestamp":"2024-09-03T10:25:43.653193","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:25:48.153236","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:25:48.153740","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:26:43.281887","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:26:43.288040","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:26:43.288399","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:26:43.289305","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:26:43.289447","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:26:43.290066","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:26:43.290745","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:26:43.290862","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:26:43.290958","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:26:43.789109","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:26:43.789274","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:26:43.789362","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:26:48.289421","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:26:48.289829","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:27:43.727455","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:27:43.733992","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:27:43.734350","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:27:43.735870","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:27:43.736018","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:27:43.736818","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:27:43.737836","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:27:43.737964","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:27:43.738059","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:27:44.235618","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:27:44.235801","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:27:44.235889","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:27:48.735986","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:27:48.736441","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:28:43.903033","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:28:43.909534","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:28:43.909920","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:28:43.910867","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:28:43.911033","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:28:43.911680","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:28:43.912400","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:28:43.912519","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:28:43.912613","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:28:44.410701","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:28:44.410875","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:28:44.410949","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:28:48.910991","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:28:48.911369","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:29:44.045319","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:29:44.051828","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:29:44.052222","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:29:44.053909","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:29:44.054076","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:29:44.054921","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:29:44.055863","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:29:44.055994","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:29:44.056090","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:29:44.553559","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:29:44.553756","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:29:44.553839","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:29:49.054028","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:29:49.054452","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:30:44.071127","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:30:44.077454","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:30:44.077854","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:30:44.079448","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:30:44.079620","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:30:44.080424","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:30:44.081411","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:30:44.081547","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:30:44.081641","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:30:44.579153","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:30:44.579349","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:30:44.579439","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:30:49.079569","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:30:49.080007","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:31:44.254844","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:31:44.263425","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:31:44.263912","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:31:44.266011","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:31:44.266213","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:31:44.267279","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:31:44.268847","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:31:44.269009","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:31:44.269116","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:31:44.765656","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:31:44.765850","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:31:44.765948","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:31:49.266125","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:31:49.266734","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:44.601963","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:44.608432","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:44.608848","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:44.610251","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:44.610417","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:44.611209","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:44.612134","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:44.612257","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:44.612358","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:45.110034","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:45.110285","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:45.110362","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:49.610378","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:32:49.610831","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:44.778321","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:44.784843","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:44.785238","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:44.786803","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:44.786964","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:44.787739","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:44.788734","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:44.788853","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:44.788948","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:45.286538","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:45.286737","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:45.286813","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:49.786921","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:33:49.787350","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:44.992680","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:45.001059","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:45.001466","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:45.003127","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:45.003332","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:45.004172","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:45.005262","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:45.005463","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:45.005561","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:45.502880","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:45.503073","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:45.503164","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:50.003247","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:34:50.003708","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:45.099663","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:45.106708","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:45.107102","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:45.108768","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:45.108939","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:45.109769","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:45.110776","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:45.110921","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:45.111018","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:45.608512","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:45.608712","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:45.608802","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:50.108892","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:35:50.109351","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:45.364453","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:45.371254","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:45.371653","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:45.373175","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:45.373334","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:45.374107","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:45.375057","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:45.375187","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:45.375281","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:45.872918","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:45.873098","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:45.873186","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:50.373300","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:36:50.373754","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:45.859226","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:45.866093","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:45.866498","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:45.868484","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:45.868663","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:45.869604","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:45.870944","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:45.871090","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:45.871193","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:46.368133","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:46.368362","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:46.368457","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:50.868602","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:37:50.869074","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:46.035155","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:46.042191","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:46.042589","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:46.044068","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:46.044251","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:46.045088","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:46.046062","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:46.046200","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:46.046305","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:46.543843","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:46.544049","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:46.544128","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:51.044203","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:38:51.044686","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:46.153981","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:46.161478","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:46.161950","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:46.163060","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:46.163240","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:46.163923","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:46.164801","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:46.164982","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:46.165086","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:46.662888","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:46.663129","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:46.663207","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:51.163172","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:39:51.163680","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:46.179053","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:46.184758","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:46.185164","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:46.186087","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:46.186233","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:46.186847","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:46.187573","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:46.187713","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:46.187807","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:46.685914","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:46.686075","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:46.686155","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:51.186192","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:40:51.186559","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:46.516325","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:46.522791","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:46.523172","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:46.524763","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:46.524923","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:46.525729","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:46.526735","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:46.526859","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:46.526958","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:47.024505","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:47.024709","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:47.024787","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:51.524875","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:41:51.525275","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:46.883593","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:46.889403","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:46.889747","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:46.891211","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:46.891361","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:46.892111","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:46.893023","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:46.893149","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:46.893248","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:47.390964","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:47.391136","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:47.391228","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:51.891333","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:42:51.891768","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:46.988595","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:46.995252","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:46.995681","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:46.996727","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:46.996880","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:46.997539","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:46.998373","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:46.998497","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:46.998596","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:47.496542","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:47.496734","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:47.496814","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:51.996853","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:43:51.997351","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:47.050490","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:47.055907","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:47.056294","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:47.057340","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:47.057494","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:47.058132","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:47.058853","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:47.058973","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:47.059068","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:47.557102","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:47.557279","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:47.557364","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:52.057455","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:44:52.057859","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:47.423686","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:47.430990","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:47.431465","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:47.433080","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:47.433263","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:47.434158","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:47.435219","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:47.435360","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:47.435463","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:47.932827","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:47.933005","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:47.933095","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:52.433216","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:45:52.433816","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:47.600455","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:47.606100","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:47.606505","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:47.607481","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:47.607640","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:47.608268","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:47.609041","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:47.609158","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:47.609251","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:48.107310","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:48.107466","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:48.107538","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:52.607614","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:46:52.608073","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:48.011620","nav_name":"req_alarm","action":"启动参数","params":"shm_name: httpub,count: 8,","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:48.017394","nav_name":"req_alarm","action":"组件启动","params":"开始验证授权....","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:48.017829","nav_name":"req_alarm","action":"组件启动","params":"授权验证完成!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:48.018792","nav_name":"req_alarm","action":"组件启动","params":"数据窗口函数-0, 定时任务函数-2","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:48.018953","nav_name":"req_alarm","action":"事件主循环","params":"PubShm 建立中","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:48.019619","nav_name":"req_alarm","action":"启动出错","params":"PubShm","operate_result":"错误","failed_reason":"[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'"}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:48.020369","nav_name":"req_alarm","action":"主函数","params":"异常退出PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'","operate_result":"错误","failed_reason":"错误跟踪Traceback (most recent call last):\n  File \"xlink_core.pyx\", line 820, in xlink_core.Main5\n  File \"\/opt\/fbi-base\/lib\/python3.11\/multiprocessing\/shared_memory.py\", line 104, in __init__\n    self._fd = _posixshmem.shm_open(\n               ^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"xlink_core.pyx\", line 1453, in xlink_core.x_start\n  File \"xlink_core.pyx\", line 830, in xlink_core.Main5\nException: PubShm:[Errno 2] No such file or directory: '\/xlink_shm_httpub_2.pub'\n"}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:48.020494","nav_name":"req_alarm","action":"停止","params":"二阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:48.020595","nav_name":"req_alarm","action":"停止","params":"三阶段开始停止!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:48.518606","nav_name":"req_alarm","action":"停止","params":"系统定时任务ip停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:48.518766","nav_name":"req_alarm","action":"停止","params":"系统定时任务st_60s停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:48.518857","nav_name":"req_alarm","action":"停止","params":"系统定时任务abroad停止完毕!","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:53.018907","nav_name":"req_alarm","action":"监控程序","params":"printf::收到消息退出","operate_result":"信息","failed_reason":""}
{"user":"x_finder3","timestamp":"2024-09-03T10:47:53.019479","nav_name":"req_alarm","action":"停止","params":"全部停止完毕!","operate_result":"信息","failed_reason":""}
